### ISSUE TITLE
Polyfill bug?: State Watcher Not Triggering in Nested Signal.State Usage

### ISSUE THREAD

**Issue by aurimasniekis** [proposal-signals/proposal-signals#110]
I'm experimenting with the polyfill code, specifically using nested `Signal.State` as shown in the following code:

```ts
const counter = new Signal.State(0);
const counterCell = new Signal.State<Signal.State<number> | undefined>(
  undefined,
);
const isEven = new Signal.Computed(() => {
  const c = counterCell.get();
  if (c) {
    return (c.get() & 1) == 0;
  }

  return null;
});
const parity = new Signal.Computed(() => {
  const r = isEven.get();
  return r === true ? 'even' : r === false ? 'odd' : 'unknown';
});

effect(() => console.log(parity.get())); // Console logs "even" immediately.
setInterval(() => counter.set(counter.get() + 1), 1000);
setTimeout(() => counterCell.set(counter), 2000);
```

However, it seems the state watcher doesn't work as expected. When `counterCell` is set to `counter` state, I expect it to trigger an update in `isEven` as it uses `counterCell.get()`, and subsequently, `parity` should also update since it depends on `isEven`. But this expected behavior is not observed. I'm not sure if this is intended or a bug. Can you please clarify or provide a fix if it's a bug?

**Comment by aurimasniekis** [comment]
Oh I think it's the `effect` I picked from example not working as expected  🤔

**Comment by aurimasniekis** [comment]
Never mind for some reason the `effect` wasn't working on vitest 😕

**Comment by EisenbergEffect** [comment]
@aurimasniekis Check the latest version of the effect example in the readme on GitHub. There were a couple typos in the code example that caused some problems. Those have been fixed on GH but the readme on NPM and the polyfill haven't been updated yet. I just want to make sure you aren't running into that.

**Comment by aurimasniekis** [comment]
Yeah, I saw those changes on the issues, but it wanst related. For some reason didn't tried yet to figure out the code doesn't run on `vitest (node)` tried on browser and it works fine. As far as I have reached looks like watcher notify method is not even called
