### ISSUE TITLE
Slimmer syntax

### ISSUE THREAD

**Issue by azder** [proposal-signals/proposal-signals#114]
Love the idea, but maybe not the interface. Is there any possibility for a slimmer syntax before everyone starts writing code like an overengineered Java design pattern?

What would be the pros/cons of something like

```
const counter = new Signal.State(0);
const isEven = new Signal.Computed(() => (counter.get() & 1) == 0);
const parity = new Signal.Computed(() => isEven.get() ? "even" : "odd");

// A library or framework defines effects based on other Signal primitives
declare function effect(cb: () => void): (() => void);

effect(() => element.innerText = parity.get());

// Simulate external updates to counter...
setInterval(() => counter.set(counter.get() + 1), 1000);
```

to be looking more like

```
// note that ~= is a placeholder sequence for any reasonable unique token

let counter ~= 0;
const isEven ~= (counter & 1) == 0;
const parity ~= isEven ? "even" : "odd";

parity.effect( value => element.innerText = value );
// or maybe even
element.innerText ~= parity;

setInterval(() => counter ~= counter + 1, 1000);
```
?

The`Signal` can still be an object (or a wrapper) with its own properties accessible like any other object (`Number`, `Function`, `Array`...), but why does it have to be with so great noise to signal ratio?

**Comment by NullVoxPopuli** [comment]
like with async/await being a "sugar" on top of promises, we need to nail down the underlying primitives before we can introduce a new syntax.

It's fine if a compiler wants to abstract over the more verbose signal API (this is actually encouraged! and most frameworks will be doing this, anyway (afaict)).

But in order to keep the proposal as focused as possible, I think it's best we keep our eyes on the behavior, and APIs as _low level primitives_, rather than something we'd expose all the way up to the average app developer (personal opinion ofc!).

If/when this proposal is accepted, folks can start thinking about proposing a syntax sugar on top of the agreed upon API

**Comment by azder** [comment]
@NullVoxPopuli in that case, the proposal can be a library/framework on top of JS until it is "nailed down" and then just added as a new syntax, instead of having multiple different ways of doing the same thing in the future, like having function declarations vs function expressions and continuously trying to impart on others to stick to expressions.

**Comment by NullVoxPopuli** [comment]
> can be a library/framework on top of JS until it is "nailed down" 

that's what the provided polyfill is

>  and then just added as a new syntax,

one thing at a time <3

>  instead of having multiple different ways of doing the same thing in the future,

we'll get there -- incrementally 🥳
Like with PRs, we don't want to have multiple focuses. When a proposal/PR has a single focus, it's much easier to discuss in isolation

**Comment by azder** [comment]
@NullVoxPopuli 
I am not suggesting to add this proposal to EcmaScript and then "one thing at a time <3" to add more to ES. I am suggesting to not add it to ES until it is ironed out as a library outside of it and only then added as the "next thing at the time"

**Comment by NullVoxPopuli** [comment]
ah ok, well in that case, I can say that the concepts have been iterated on for the at _least_ 5 years in various javascript ecosystems: Svelte, Solid, Vue, Ember, MobX, etc (I think more are listed out in the README) -- all the learnings from those ecosystems have come together to make this proposal as well as the current polyfill.

**Comment by azder** [comment]
@NullVoxPopuli if the concepts have been iterated, then it is superflous to just iterate once more with a more cumbersome object syntax (`new`, `.get()`, `.set()`) and could just move to adding what you already know it works, but with a slimmer syntax.

**Comment by NullVoxPopuli** [comment]
this proposal _is_ what you're asking for, tho pre-adding a bunch of custom sigils to the language. The learnings of the last many years have come together to make this proposal, and it's what we're trying to get final alignment / agreement on.

**Comment by azder** [comment]
I am not asking of pre-adding anything to the language. I am asking for the opposite - adding only a minimal well tested change. 

I am wary of the few years difference between the addition of `Promise` and `async`/`await` resulting in still having to deal a lot of code using `.then().catch()` today, year after the syntax sugar had been added simply because many still use the cumbersome `Promise` object directly.

I consider that this proposal will result in us still dealing with code like `new Signal.State(0)` 10 years from now even if a year after this proposal, some operator or two like `~=` are added.

**Comment by EisenbergEffect** [comment]
We had some syntax discussions early on. There's definitely interest. Svelte has been involved from the beginning, for example. They are doing some work in this space via their compiler.

However, there has been a big concern that tying the signals proposal to a particular syntax for the initial version, would likely ruin the chance of standardization. Syntax changes in JS bring about a massive additional set of baggage. I don't think TC39 would consider approaching this feature in a syntax-first sort of way. The approach of going with a library first and then layering on syntax later, is the normal strategy these days, in my understanding.

Additionally, our research and discussions made it clear that most frameworks need direct manipulation through the API surface. Not everything can be accomplished through a syntax. In the same way today that there are very legitimate use cases for constructing a Promise, outside of using async/await. So, the library capabilities are required either way. And it's the easiest way to validate that the semantics are correct. It's much easier to have folks test out a library then to go updating Babel and TypeScript every other week when something changes.

**Comment by EisenbergEffect** [comment]
And just to re-iterate...I'm very much for syntax and very much for DOM integration. I'm not sure we want to tie those things to this proposal, though.

**Comment by azder** [comment]
> The approach of going with a library first and then layering on syntax later, is the normal strategy these days, in my understanding.

@EisenbergEffect  Just to be clear, I use "library" in a sense of not part of EcmaScript. Are you using it the same way or are you considering it as part of the language standard library?

My concern above is more or less in terms of what are the pros/cons of going one way or another. 

1. A big con I noted above was some general focus/defocus concern w.r.t this proposal. 

2. My pro was in the sense of instead of focusing on frameworks above JS, the focus would be of not making a fully exposed (no attempt of abstraction) C++ style of code/API in EcmaScript, but to having EcmaScript abstract away from what looks like an engine concern, thus making code written simpler, leaner with removing the possibility of cumbersome `new Signal.State(0)`

3. Your concern is that you want this proposal to not be stopped because you want to standardize anything as long as it is standard? 

Help me with this last one. Why the need of having a standard in any form as soon as possible? Do you want to move frameworks to use the same EcmaScript API? Maybe that's the difference we are having, you focus on frameworks at the expense of the language, I focus on the language at the expense of frameworks.

Oh, and one important thing, is that a pro or a con for having a slimmer syntax instead of any kind of syntax with one more added later on?

**Comment by NullVoxPopuli** [comment]
> I'm very much for syntax

I am as well! I'm cautious of syntax changes because the last _syntax_ that I'm aware of that's tried to ship ([decorators](https://github.com/tc39/proposal-decorators)) has taken many many many many years (7 years!)-- it still hasn't shipped, but it's at least close now.

**Comment by EisenbergEffect** [comment]
When I say library, I'm talking about the language standard library. We have the polyfill now as an independent library to help with validation. This alone will not solve the interoperability problem though, as mentioned in the proposal itself. Some form of built-in is required for that.

My concern is not the speed at which this is standardized. I worked on decorators starting in late 2014. My concern is that tying signals to a syntax will be a non-starter. Nothing will ever get standardized that way. This is based on guidance from TC39 members. My own experience with engine implementors tells me that they care a lot more about the algorithms being rock solid with no room for interpretation. Getting consensus on that is hard enough without bringing syntax into the conversation, something that almost always results in a lot of bike shedding right out of the gate.

My other concern is that a pure syntax without an API will not meet the minimum needs of the stakeholders. Absolutely everything present in the API is connected to a real-world use case gathered from conversations with dozens of library and framework authors. The semantics and core capabilities are what is important to ensure that we ship something that actually can be used. If we fail at that, no amount of syntax is going to fix things.

**Comment by ljharb** [comment]
(lots of syntax has shipped in the last 7 years, but syntax indeed takes much longer and is much more costly)

**Comment by littledan** [comment]
Decorators over local variables would be an interesting generalization here, in my opinion. But several TC39 delegates have expressed concerns about any system which would lead to side effects from reading or writing local variables. The goal to avoid this pattern would rule out your syntax as well, unfortunately.

**Comment by azder** [comment]
@littledan wasn't a syntax I proposed, but that's informative about the decorators none the less. It is more like a token example in order to get the idea across. @EisenbergEffect comments provided me with better understanding about the hurdles that exist in general.

Dishearthening as much as informative.

I guess JS will go further on its way of being compiler (LLM generator) target, albeit slowly. I will just have to try and find some human focused subset of JS, be it ES or a language that compiles to it as many (and I guess many more will) jump ship to TS, JSX/TSX or other languages transpiled to it as well.

No more need of this issue. Whenever a time comes, I'm sure others will raise a similar one.

**Comment by NullVoxPopuli** [comment]
@azder have you seen the decorator syntax version of signals? it's quite good and doesn't require a custom additional syntax!

Using both the included in this proposal: https://www.npmjs.com/package/signal-polyfill, and my own wrapper / collection of examples: https://www.npmjs.com/package/signal-utils
We can make reactive UI like this: 
```js
import { signal } from 'signal-utils';

class State {
    @signal accessor #value = 3;

    get doubled() {
        return this.#value * 2;
    }

    increment = () => this.#value++;
}

let state = new State();


// output: 6
// button clicked
// output: 8
<template>
  <output>{{state.doubled}}</output>
  <button onclick={{state.increment}}>+</button>
</template>
```
which, I quite like!
The only non-standard thing[^non-standard] you'd see at first is the `@signal` decorator, and everything else is the same javascript you already know 

 :tada: 

[^non-standard]: and by non-standard, I mean "not built in", and not proposed to be built in, but decorators in general are nearly there!

**Comment by azder** [comment]
sorry @NullVoxPopuli I do not consider decorattor as a good syntax. Maybe if they are made to work everywhere, but even then, I find it a bit clunky in design simply because it was kept as such for the sake of seeming familliar to people who use(d) other languages

**Comment by NullVoxPopuli** [comment]
> beyond fields in classes

what do you mean?

> Maybe if they are made to work everywhere

that _is_ the whole point of the proposal

> I find it a bit clunky in design simply because it was kept as such for the sake of seeming familliar to people who use(d) other languages.

this is not true :sweat_smile:
